apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-certificate
  namespace: traefik
spec:
  secretName: ld-tls-secret
  issuerRef:
    name: traefik-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - ld.bearjordan.home
