apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-certificate
spec:
  secretName: portainer-certificate
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - ptr.bearjordan.dev
