apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
