apiVersion: v1
data:
  api-token: ENC[AES256_GCM,data:VFUydxYGzr5AjrSXjDANtVbQUWARWWLc2ntc9M7QljYd19YYHtanQ8XmurBXwijx9m4HCQ==,iv:rUI562mc41hFsWBFwCg9XkBILxCXiE7NcJhYx9oCpGk=,tag:z/ADgw/Las+5JR3gJKlTfw==,type:str]
kind: Secret
metadata:
  name: cloudfare-api-key
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19kaqnwyntssdv95us7a7jqyt6j606alnm3pwcfzft9fnphrv8deq8p6ecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb25HVHc5dkFMaWNRYm5x
        NzRMVVRSY0JYbEt5U0lzNUc1NjBPdmNZSWxnCnlNMGdhRUJZT05sY25oYmlqYzV1
        UVdaeThrUnc0N2twekMraXJsZEE5VFEKLS0tIFNOYWpPVzE0OHB5YW9aUnRJcHd6
        Ylp4ZWtmMTlUMTd6RjA4K1FwSGdmbW8K8LvUix7zHEmk4IiW+oyCoEtZo0oY1K7p
        LsGXhePC1SCepzf/B8TPr5gYYhuV+LJUV8KQcvgK9EHcQhdlu7ibkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-03T02:14:11Z"
  mac: ENC[AES256_GCM,data:gufSa6gWvshW+Eirqb/y/197CdOJSZQsZW7KiDDDwuSHHy+9/Tndtmt9+NqjNv6bDdW6JN8+lcu7ayjC8rZUfG3K48HIvpDMxTCzGNTJ5qqz8iMyInhkVlUehqgYGxgOoLbOtMq4ZRUiA5HiEuWEgw6oMOJI2jGZXWYCPq1lm8g=,iv:vT1sZ6hIfFfNuV5fg3OtLv8qeApq2OVso7mQxXjzarg=,tag:dSRnBI5dN18yxeYz4IbMIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
