# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: traefik-certificate
#   namespace: traefik
# spec:
#   secretName: example-tls-secret
#   issuerRef:
#     name: traefik-clusterissuer
#     kind: ClusterIssuer
#   dnsNames:
#     - foo.bearjordan.home

