apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
  interval: 1m0s
  values:
    replicaCount: 1
    serviceAccount:
      create: true
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
