apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-certificate
  namespace: traefik
spec:
  secretName: rook-tls-secret
  issuerRef:
    name: traefik-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - rook.bearjordan.home
