apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg-cluster
spec:
  chart:
    spec:
      chart: cluster
      version: 0.2.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
  interval: 1m0s
  values:
    type: postgresql
    version:
      postgresql: "16"
    cluster:
      instances: 3
      storage:
        size: 8Gi
        storageClass: ""
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 2000m
          memory: 2Gi
      enableSuperuserAccess: true
      enablePDB: true

      monitoring:
        enabled: true
        podMonitor:
          enabled: true
        prometheusRule:
          enabled: true

      initdb:
        database: dev
        owner: dev
        secret:
          name: dev-secrets
        encoding: UTF8
        postInitSQL:
          - CREATE EXTENSION IF NOT EXISTS vector;
