apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unifi-network
  name: unifi-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-network
  template:
    metadata:
      labels:
        app: unifi-network
    spec:
      containers:
        - image: lscr.io/linuxserver/unifi-network-application:latest
          name: unifi-network
          ports:
            - containerPort: 8443
            - containerPort: 8080
            - containerPort: 3478
              protocol: UDP
            - containerPort: 10001
              protocol: UDP
          volumeMounts:
            - name: unifi-data-pvc
              mountPath: /config
          envFrom:
            - secretRef:
                name: mongo-credentials
            - configMapRef:
                name: config
      volumes:
        - name: unifi-data-pvc
          persistentVolumeClaim:
            claimName: unifi-data-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  PUID: "1000"
  PGID: "1000"
  TZ: Etc/UTC
  MONGO_PORT: "27017"
  MONGO_DBNAME: unifi
  MONGO_USER: unifi
  MONGO_HOST: mongodb-replica-set-0.mongodb-replica-set-svc.mongodb.svc.cluster.local,mongodb-replica-set-1.mongodb-replica-set-svc.mongodb.svc.cluster.local,mongodb-replica-set-2.mongodb-replica-set-svc.mongodb.svc.cluster.local
  MONGO_AUTHSOURCE: unifi
  MONGO_REPLICASET: mongodb-replica-set
  MONGO_SSL: "false"
