apiVersion: v1
data:
  MONGO_PASS: ENC[AES256_GCM,data:FPHrd2d7QLHpjHjGKhqCfahmzQ70Ey7I5YDckQ==,iv:sxf6FzKvwcbXpoH0LptCIdFzbVxF6QYgg06jl64jq40=,tag:Zx++NQth4RSzBRX1WMMjsQ==,type:str]
kind: Secret
metadata:
  name: mongo-credentials
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19kaqnwyntssdv95us7a7jqyt6j606alnm3pwcfzft9fnphrv8deq8p6ecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bnJwNFo0T2lhb2RIbEpB
        d2dlSnczZ1NWOHVTT1FvWWlqdFAwcGUxUjE4ClcrSjZ5OGdYYU8ycDgyeXYzY3VM
        RVdsSE5yeE9IczR1ZXUwNHU0TkpQUTgKLS0tIE5LQlhybzNKSTNOMm1pTWZNbUxx
        bFFob3Mvazk1am9UUDRmUDdSVUpkaU0KgGEETDEKTUc+hZxW4pu6eRfteNr9UQb5
        WdVllyGpu/GZeO/MK+JokmnzLVSmBPrHF5iHUXiPjdXZwrFHo3DMlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-01T23:52:44Z"
  mac: ENC[AES256_GCM,data:dMW8Sh/MVDU2WXHIchgU0GZbTm5dI8E/UeE+XVKs8wIqyXZxKoJaMUxsMTZiaEzDGsz+tVeDfx0ttLTQKOGwvzWrpyHhIY5AV+apUaqh2In6ozq43VgmCQNmrMS/jYySHYEqXVCOiFPkmnjMKPU9TezMj5LrH6tgdJybJ2vlc0E=,iv:T1/UAV8gHDP5Q4j9u5rUS49houbzBsxlzyJcBknebas=,tag:Te6CPIALwKE5ibJb851OYg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
