apiVersion: v1
data:
  MONGO_PASS: ENC[AES256_GCM,data:xjULgMDOKUxQed1IAbiX88wpv4q6fhzsBrGT0A==,iv:TU9+lLqhbWt8AZ9EWfnrtznuMp4nDhddbk3nped+lyE=,tag:O0+Y32q1tYnX53Ro+iJRdQ==,type:str]
kind: Secret
metadata:
  name: mongo-credentials
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19kaqnwyntssdv95us7a7jqyt6j606alnm3pwcfzft9fnphrv8deq8p6ecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K0hZQXd3M1dnbXlwekVI
        SThjd1hORmtHQUZ6NmgxL0xUbExkZkNldEZVClNGYWxJczVvNlhpeGR5V0h6L2dV
        UGh1b0xYclBLZEFwcUlQa3VkNXowOUkKLS0tIE5sWVVEZUx0UWNoRjdOcGhSbnhI
        Ykphc2NaeTcwejZuTVJyUlRXL3RWYVEKgPmWVuflIFENdEzIDToWCPmDbh8L5aMT
        i1frFM+NzLn30WVhOH3h/uKcml1v+vO9kZlWsqzT1RbUx8Z2NvStaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T00:22:18Z"
  mac: ENC[AES256_GCM,data:AfhU8WjyI2DmoeyJwzWhiupw/qaTKOOYonjLnoZk9Lj7xxUdO5BS0RWQESsVphhkGVfKb0k01RMsuD/dz9wJlXGzdjvQaJ1WD1juYVmijnpJdOqhLaJ6dAOMEmUIhmN6rxrKpawzb/sWSiLqgxA+e8sqZdrCd3CNFR8yIOp2k5o=,iv:5JgtF+GuivEzO3LYbwwFiDjNedoCLMwLiVP+J6N4lhY=,tag:aXlzzzotvvJywdjfbA0B0g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
