apiVersion: v1
kind: Service
metadata:
  labels:
    app: unifi-network
  name: unifi-svc
spec:
  ports:
    - name: web-admin
      port: 8443
      protocol: TCP
    - name: device-communication
      port: 8080
      protocol: TCP
    - name: stun
      port: 3478
      protocol: UDP
    - name: ap-discovery
      port: 10001
      protocol: UDP
  selector:
    app: unifi-svc
  type: ClusterIP
