apiVersion: v1
kind: Service
metadata:
  labels:
    app: unifi-svc
  name: unifi-svc
spec:
  ports:
    - port: 8443
      protocol: TCP
    - port: 8080
      protocol: TCP
    - port: 3478
      protocol: UDP
    - port: 10001
      protocol: UDP
  selector:
    app: unifi-svc
  type: ClusterIP
