apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkding
  name: linkding
  namespace: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      containers:
        - image: sissbruecker/linkding:1.39.1
          name: linkding
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: linkding-data-pvc
              mountPath: /etc/linkding/data
          envFrom:
            - secretRef:
                name: linkding-credentials
      volumes:
        - name: linkding-data-pvc
          persistentVolumeClaim:
            claimName: linkding-data-pvc
