apiVersion: v1
data:
  LD_SUPERUSER_NAME: ENC[AES256_GCM,data:CN2Tshq27os=,iv:IM9GykmBxlW3JpeXOZ86M8HTSc89nUi61EVhrmo938g=,tag:zPYlLQVZ1cV4dxPvCE1ktw==,type:str]
  LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:9IEL06JipgymCXQw,iv:tqTCOKr7TG4VsTpxFR3a+YEnNf3xsCC41Tq8jnE8FH0=,tag:60Itxk43fCQ8GGl7sTYBAw==,type:str]
kind: Secret
metadata:
  name: linkding-credentials
  namespace: linkding
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19kaqnwyntssdv95us7a7jqyt6j606alnm3pwcfzft9fnphrv8deq8p6ecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSVNUSW45UjJYckdOOFhr
        Sll2T3VtTm9WMTNkYUdxK01MRmdDZS9SWkNzCmRiTmhmOGFybHFZREt2SUxpMW44
        UFRjOWpabkVXTlBNeWMza0x0OURxYmcKLS0tIDJWU0pEM0p2anRwYmFGdmJZK0w1
        YlV3eEt5R3hKQlBxcUpZcXlIZjNkWWMKVlACa0V5RnviArvrKq59het+RTX1iIJY
        2LrdHhsbkuIt2W3lTZ6GwtutFgduQjOOgZ2HDG5fByYl8/5wcQAy2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-29T00:26:48Z"
  mac: ENC[AES256_GCM,data:r7uYoxhbIZvqBxbELV6rKDxz8GlsuqeTmtKAwv1Ft1LST4v7aZhgTeYRA6nD1rKClqI2SS3A/uAtW9mKa8gjO7xL0ZLy6BzKBFc1Rwz2VMTBhHB5K7iQIzQuvp71zcll4hzmhBJcfq64N43DOP7OLsFJeLWG928utz1xZ1Zzq4s=,iv:Ze3EdUO1bLOesgOTO8qmc/QYf2l8R58ag7dg96DmOoI=,tag:K93OrdSk5bB6kjuS5Tb9DQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
