apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-crd
spec:
  chart:
    spec:
      chart: community-operator-crds
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mongodb
      version: 0.12.0
  interval: 1m0s
