apiVersion: v1
data:
    auth.rootPassword: ENC[AES256_GCM,data:GhH4WxfuNwZqFpjkZ7Y/8NuF4HFQ7uW4TxTSMg==,iv:NbDPfQNmClKVBXRXIK4pP1bQ7BrLcArxOqlGUrEdVCw=,tag:LLV+dqQmIQ5DCYrHSMfLLA==,type:str]
kind: Secret
metadata:
    name: mongodb-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19kaqnwyntssdv95us7a7jqyt6j606alnm3pwcfzft9fnphrv8deq8p6ecm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YWxGSVBLMlJWRUlsdTBJ
            SG9rTmdydzNNZlF2Nlhoek1BZ0pETWRrWGlBCjk5NGwrbkpEK2FNVldwSDNlYUox
            VnV0VEtMZGRXWXRHNjJqbXlkYkdtT1kKLS0tIGExMHpEaDBwblNMUzRIcVg1M2U2
            UEZKT3I5SzJaZ1FPS0dpTS9ibkdWdTgKBZQQOwP4lVw8ki2ycKSk01KEZsWDAtmO
            ZmfiHzinygrqRe61oSqMuOZh8WtVaCszRBU77cmFE0D4zg62hTfYgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-02T01:27:14Z"
    mac: ENC[AES256_GCM,data:3J0V0CUlyw3Ed0JJsAcGM/HglaaU8G9ujwP83+2iN90LWjQFyD/B3F597H62abf+xUMDCPwtZJY/dXkrX4Gde37FTA6vzLPGOVmFOdd80XmpVEWlP4NJbrF024ecPZuPc24ThOt1/nROFEf1/Z/705o7NviHvJ2YZXmHQ6hgrFQ=,iv:nTc9gQFGDYKmqlDkBUBuoGKZl4k5AYzDDH0uM13NVsg=,tag:IaVd4a2vM9BMHkhicvtvDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
