apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
spec:
  chart:
    spec:
      chart: community-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mongodb
      version: 0.12.0
  interval: 1m0s
  values:
    operator:
      version: 0.12.0
      watchNamespace: "*"
      resources:
        limits:
          cpu: 1100m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 200Mi
    database:
      name: mongodb-database
      namespace: mongodb
    createResource: true
    resource:
      users:
        - name: admin
          db: admin
          passwordSecretRef:
            name: admin-credentials
          roles:
            - name: clusterAdmin
              db: admin
            - name: userAdminAnyDatabase
              db: admin
            - name: readWriteAnyDatabase
              db: admin
            - name: dbAdminAnyDatabase
              db: admin
          scramCredentialsSecretName: admin-scram
          connectionStringSecretName: admin-connection
        - name: unifi
          db: unifi
          passwordSecretRef:
            name: unifi-credentials
          roles:
            - name: readWrite
              db: unifi
            - name: dbAdmin
              db: unifi
            - name: userAdmin
              db: unifi
          scramCredentialsSecretName: unifi-scram
          connectionStringSecretName: unifi-connection
