apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mongodb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: 16.4.11
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: mongob-credentials
  values:
    auth:
      enabled: true
      rootUser: root
    persistence:
      enabled: true
      name: mongodb-pvc
      size: 1Gi
      mountPath: /bitnami/mongodb
    metrics:
      enabled: true
