apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  ingressClassName: traefik
  rules:
    - host: unifi.bearjordan.home
      http:
        paths:
          - backend:
              service:
                name: unifi-network
                port:
                  number: 8443
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - unifi.bearjordan.home
      secretName: unifi-tls-secret
