apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: unifi-https-middleware
  namespace: unifi-network
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: unifi-transport
  namespace: unifi-network
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: unifi-ingress
  namespace: unifi-network
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.bearjordan.home`)
      kind: Rule
      services:
        - name: unifi-network
          port: 8443
          scheme: https
          serversTransport: unifi-transport
  tls:
    secretName: unifi-tls-secret
